runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT get_data_app:app
service: default

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: dpd-opendata
    #SODA_DALLAS_APPTOKEN:
#[END env]

handlers:
- url: /ingest
  script: get_data_app.app

- url: /.*
  script: get_data_app.app